"""Shared configuration. Local paths and settings only, no secrets."""

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent

DATA_DIR = PROJECT_ROOT / "data"
PROTOCOLS_DIR = DATA_DIR / "protocols"
TEST_CASES_DIR = DATA_DIR / "test_cases"
VECTOR_STORE_DIR = DATA_DIR / "vector_store"  # generated by ingestion
REVIEW_LOG_PATH = DATA_DIR / "review_log.jsonl"  # generated by review

# Knowledge layer
EMBEDDING_MODEL_NAME = "all-MiniLM-L6-v2"  # small, CPU-friendly
CHUNK_SIZE_CHARS = 800
CHUNK_OVERLAP_CHARS = 150
RETRIEVAL_TOP_K = 5

# Shown with every gap list, and attached to each generated item.
# The tool reports missing information only. It does not make clinical decisions.
DISCLAIMER = (
    "This is an automated information-gap analysis, not a clinical assessment, "
    "diagnosis, or treatment/component recommendation. Every item is a "
    "suggestion that requires review by a qualified prosthetics specialist."
)
