"""Shared configuration. Local paths and settings only, no secrets."""

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent

DATA_DIR = PROJECT_ROOT / "data"
SOURCES_DIR = DATA_DIR / "sources"  # knowledge documents (PDFs not in git)
CATALOG_PATH = SOURCES_DIR / "catalog.json"  # which documents to ingest
# Folders under SOURCES_DIR kept for the project but never ingested: the
# download registry, AI safety/regulation references, and gait datasets.
SOURCES_NOT_INGESTED = ("00_registry", "04_ai_safety_regulation", "05_datasets")
EXTRACTED_DIR = DATA_DIR / "extracted"  # cleaned text per document, generated
TEST_CASES_DIR = DATA_DIR / "test_cases"
VECTOR_STORE_DIR = DATA_DIR / "vector_store"  # generated by ingestion
CASES_DIR = DATA_DIR / "cases"  # one JSON file per case, written by intake (shared/store.py)
REVIEW_LOG_PATH = DATA_DIR / "review_log.jsonl"  # generated by review
# Material for the specialist trial: the Arabic term sheet, the prepared
# cases (trial/cases/), and the report built from the review log.
TRIAL_DIR = DATA_DIR / "trial"

# Knowledge layer
# Multilingual (Arabic, English, German and 100+ more), about 2.3 GB, MIT
# licence. The revision pins the exact model version so vectors stay
# comparable. Changing either means re-running `python -m knowledge.ingest`.
EMBEDDING_MODEL_NAME = "BAAI/bge-m3"
EMBEDDING_MODEL_REVISION = "5617a9f61b028005a4858fdac845db406aefb181"
EMBEDDING_MAX_TOKENS = 512  # a chunk of 800 characters is well under this
CHUNK_SIZE_CHARS = 800
CHUNK_OVERLAP_CHARS = 150
RETRIEVAL_TOP_K = 5  # passages retrieved per missing field
# Languages of the documents searched for gaps. German ("de") was left out
# on 2026-10-06: on four test cases it added no citation English or Arabic
# didn't already give, and it cost 1 of 8 Arabic evaluation queries (see
# FUTURE_WORK.md). The German documents stay ingested, so adding "de" back
# needs no re-ingest.
RETRIEVAL_LANGUAGES = ("en", "ar")
# A retrieved passage is cited for a gap only if its similarity score is at
# least this AND it mentions the field's topic (shared/field_guide.py).
# Set from `python -m knowledge.evaluate` with bge-m3 (2026-10-06): correct
# answers scored 0.58 or more, off-topic text at most 0.44.
MIN_RELEVANCE_SCORE = 0.50
EVAL_QUERIES_PATH = DATA_DIR / "eval" / "retrieval_queries.json"
# Only documents whose catalog "domains" include one of these are searched.
# v1 is use case 01 (amputation), so orthotics-only documents are skipped.
RETRIEVAL_DOMAINS = ("prosthetics",)
# Catalog ids of documents the gap search leaves out. They stay ingested, so
# searching one again needs no re-ingest, and the hand-written statements in
# reasoning/ can still quote them. The ICRC gait-analysis manual was left out
# on 2026-10-09: searched, it changed 28 of the 102 lower-limb gap citations
# (12 test cases), most to page-header or table residue, replaced VA/DoD
# guideline quotes for comorbidities, and cost 1 of 8 Arabic evaluation
# queries (see FUTURE_WORK.md, design and fitting).
RETRIEVAL_EXCLUDED_DOCUMENTS = ("prosthetic_gait_analysis_icrc_manual_2014",)

# Shown on every review page. The tool reports missing information and quotes
# what its sources say about components, design and fitting; it does not make
# clinical decisions. Revised 2026-10-08 when component statements were added
# (was: "missing information only"), and 2026-10-09 for design and fitting.
DISCLAIMER = (
    "This is automated decision support, not a clinical assessment, diagnosis "
    "or prescription. It lists intake information that appears to be missing "
    "and quotes what the guidelines and manuals in its source library say "
    "about this case's prosthetic components, design and fitting, each with "
    "the source's own grade where it gives one. It does not choose or rank "
    "components. It does not judge whether the patient is ready for fitting. "
    "Every item requires review by a qualified prosthetics specialist, who "
    "makes the decision. The lists may be incomplete: a field that is not "
    "listed has not been checked for adequacy, only for being filled in, and "
    "only statements in the source library are shown."
)
